//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
using System.ComponentModel.DataAnnotations.Schema; // For NotMappedAttribute

namespace Assignment2.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forums()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte[] Avatar { get; set; }
      

        [NotMapped]
        public HttpPostedFileBase AvatarFile { get; set; } // 用于文件上传的额外属性

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }

    }
}
