//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int Id { get; set; }
        public Nullable<int> ForumId { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual Forums Forums { get; set; }
        // 添加以下属性
        public string ForumTitle { get; set; }

        
    }
}
